<?php

namespace AppBundle\Repository;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByTitle()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT todo FROM AppBundle:Todo todo ORDER BY todo.title ASC')
            ->getResult();
    }
}
